{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "support_functions.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/EleonoraBartolomucci/Fairness/blob/master/support_functions.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "6-GtXfILY6qy",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 280
        },
        "outputId": "c123591b-f610-471a-96db-5645355088e2"
      },
      "source": [
        "!pip install clarifai"
      ],
      "execution_count": 26,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: clarifai in /usr/local/lib/python3.6/dist-packages (2.6.2)\n",
            "Requirement already satisfied: protobuf<4,>=3.6 in /usr/local/lib/python3.6/dist-packages (from clarifai) (3.10.0)\n",
            "Requirement already satisfied: requests<3,>=2.13 in /usr/local/lib/python3.6/dist-packages (from clarifai) (2.23.0)\n",
            "Requirement already satisfied: configparser<4,>=3.5 in /usr/local/lib/python3.6/dist-packages (from clarifai) (3.8.1)\n",
            "Requirement already satisfied: googleapis-common-protos<2,>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from clarifai) (1.52.0)\n",
            "Requirement already satisfied: jsonschema<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from clarifai) (2.6.0)\n",
            "Requirement already satisfied: grpcio<2,>=1.13.0 in /usr/local/lib/python3.6/dist-packages (from clarifai) (1.29.0)\n",
            "Requirement already satisfied: future<2,>=0.15 in /usr/local/lib/python3.6/dist-packages (from clarifai) (0.16.0)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf<4,>=3.6->clarifai) (47.3.1)\n",
            "Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.6/dist-packages (from protobuf<4,>=3.6->clarifai) (1.12.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.13->clarifai) (2020.4.5.2)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.13->clarifai) (1.24.3)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.13->clarifai) (2.9)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.13->clarifai) (3.0.4)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Jl0nPnD7VUxo",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "from pydrive.auth import GoogleAuth\n",
        "from pydrive.drive import GoogleDrive\n",
        "from google.colab import auth\n",
        "from oauth2client.client import GoogleCredentials\n",
        "from clarifai.rest import ClarifaiApp\n",
        "from clarifai.rest import ApiError\n",
        "import numpy as np\n",
        "import time\n",
        "import json\n",
        "import csv\n",
        "import random\n",
        "import pandas as pd\n",
        "import requests\n",
        "from lxml import html\n",
        "import shutil\n",
        "import os\n",
        "import json\n",
        "\n",
        "\n",
        "# AUTHENTICATE IN GOOGLE DRIVE\n",
        "def authenticate():\n",
        "  auth.authenticate_user()\n",
        "  gauth = GoogleAuth()\n",
        "  gauth.credentials = GoogleCredentials.get_application_default()\n",
        "  drive = GoogleDrive(gauth)\n",
        "  return drive\n",
        "drive = authenticate()\n",
        "\n",
        "\n",
        "def create_folder_in_drive(gdrive, folder_name, parent_folder_id):\n",
        "  folder_metadata = {'title': folder_name,'mimeType': 'application/vnd.google-apps.folder',\n",
        "                    'parents': [{\"kind\": \"drive#fileLink\", \"id\": parent_folder_id}]\n",
        "                    }\n",
        "  folder = gdrive.CreateFile(folder_metadata)\n",
        "  folder.Upload()\n",
        "  print(folder)\n",
        "  # Return folder informations\n",
        "  print('title: %s, id: %s' % (folder['title'], folder['id']))\n",
        "  return folder['id']\n",
        "\n",
        "\n",
        "def drop_unnamed(df):\n",
        "  cols = [c for c in df.columns if c.lower()[:7] != 'unnamed']\n",
        "  return df[cols]\n",
        "\n",
        "\n",
        "def upload_file(filename, folder_id):\n",
        "  drive = authenticate()\n",
        "  fileList = drive.ListFile({'q': \"'\" + folder_id + \"' in parents and trashed=false\"}).GetList()\n",
        "  drive_file = drive.CreateFile({'title': filename, 'parents': [{'id': folder_id}]})\n",
        "  # Check if file already exists in Google Drive (prevents duplicates)\n",
        "  for file in fileList:\n",
        "      if file['title'] == filename:  # The file already exists, then overwrite it\n",
        "          fileID = file['id']\n",
        "          drive_file = drive.CreateFile({'id': fileID, 'title': filename, 'parents': [{'id': folder_id}]})\n",
        "  # Upload user picture on Google Drive\n",
        "  drive_file.SetContentFile(filename)  # path of local file content\n",
        "  drive_file.Upload()  # Upload the file.\n",
        "  return drive_file['id']"
      ],
      "execution_count": 27,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "NHBNPUGlbzWn",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "################################################################################\n",
        "######################### DOWNLOAD RANKINGS ####################################\n",
        "\n",
        "def get_ranking_from_call(url_business, lang, sort, query):\n",
        "    headers = [{\"name\": \"Accept\", \"value\": \"*/*\"}, {\"name\": \"Accept-Encoding\", \"value\": \"gzip, deflate, br\"},\n",
        "               {\"name\": \"Accept-Language\", \"value\": \"it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3\"},\n",
        "               {\"name\": \"Connection\", \"value\": \"keep-alive\"},\n",
        "               {\"name\": \"Content-Type\", \"value\": \"application/x-www-form-urlencoded; charset=utf-8\"}, {\"name\": \"Cookie\",\n",
        "                                                                                                       \"value\": \"qntcst=D; hl=en_US; wdi=1|3C26116D69138F61|0x1.78d019f71a444p+30|a7756ff94751d3a9; _ga=GA1.2.3C26116D69138F61; location=%7B%22city%22%3A+%22New+York%22%2C+%22state%22%3A+%22NY%22%2C+%22country%22%3A+%22US%22%2C+%22latitude%22%3A+40.713%2C+%22longitude%22%3A+-74.0072%2C+%22max_latitude%22%3A+40.8523%2C+%22min_latitude%22%3A+40.5597%2C+%22max_longitude%22%3A+-73.7938%2C+%22min_longitude%22%3A+-74.1948%2C+%22zip%22%3A+%22%22%2C+%22address1%22%3A+%22%22%2C+%22address2%22%3A+%22%22%2C+%22address3%22%3A+null%2C+%22neighborhood%22%3A+null%2C+%22borough%22%3A+null%2C+%22provenance%22%3A+%22YELP_GEOCODING_ENGINE%22%2C+%22display%22%3A+%22New+York%2C+NY%22%2C+%22unformatted%22%3A+%22New+York%2C+NY%2C+US%22%2C+%22accuracy%22%3A+4.0%2C+%22language%22%3A+null%7D; xcj=1|Ptt9P03gfc75x_PBT9zmqCkUuSuyB7PR-wWUBvABNi4; __qca=P0-60561249-1581956668708; G_ENABLED_IDPS=google; __cfduid=db8764ff59d8028a6c2e1b214867927d81583160194; _gid=GA1.2.2014867238.1583835527; bse=05dcd9d5de304ef0b1d9a76fa768b10f; sc=8a1ca0dbc2; pid=505721aa4569e7bb\"},\n",
        "               {\"name\": \"Host\", \"value\": \"www.yelp.com\"},\n",
        "               {\"name\": \"Referer\", \"value\": \"https://www.yelp.com/biz/noche-de-margaritas-new-york\"},\n",
        "               {\"name\": \"TE\", \"value\": \"Trailers\"}, {\"name\": \"User-Agent\",\n",
        "                                                     \"value\": \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0\"},\n",
        "               {\"name\": \"X-Requested-By-React\", \"value\": \"true\"},\n",
        "               {\"name\": \"X-Requested-With\", \"value\": \"XMLHttpRequest\"}]\n",
        "    headers_ok = {}\n",
        "    for header in headers:\n",
        "        temp = {\n",
        "            header['name']: header['value']\n",
        "        }\n",
        "        headers_ok.update(temp)\n",
        "\n",
        "    x = 0\n",
        "    reviews_list = []\n",
        "    position = 1\n",
        "    url = url_business + \"/review_feed?rl=\" + lang + \"&sort_by=\" + sort + \"&q=\" + query\n",
        "\n",
        "    while 1:\n",
        "        if x == 0:\n",
        "            page_load = requests.get(url + '&start=', headers=headers_ok)\n",
        "        else:\n",
        "            page_load = requests.get(url + '&start=' + str(x), headers=headers_ok)\n",
        "        print(page_load)\n",
        "        x = x + 20\n",
        "        reviews = page_load.json()['reviews']\n",
        "        # print(json.dumps(reviews, indent=4, sort_keys=True))\n",
        "        if not reviews:\n",
        "            break\n",
        "        for review in reviews:\n",
        "            reviews_list.append((position, review['userId'], review['user'],\n",
        "                                 review['comment'], review['feedback'],\n",
        "                                 datetime.datetime.strptime(review['localizedDate'], '%m/%d/%Y')))\n",
        "            position = position + 1\n",
        "    df_reviews = pd.DataFrame(reviews_list, columns=[\"position\", \"user_id\", \"user\",\n",
        "                                                     \"comment\", \"feedback\", \"date\"])\n",
        "    return df_reviews\n",
        "\n",
        "\n",
        "def retrieve_rankings(business_id, folder_id):\n",
        "    df_rel_ranking = get_ranking_from_call(\"https://www.yelp.com/biz/\" + business_id, \"en\", \"relevance_desc\", \"\")\n",
        "    df_date_ranking = df_rel_ranking.sort_values(by=['date']).reset_index(drop=True)\n",
        "    df_date_ranking['position'] = df_date_ranking.index + 1\n",
        "    df_rand_ranking = df_rel_ranking.sample(frac=1).reset_index(drop=True)\n",
        "    df_rand_ranking['position'] = df_rand_ranking.index + 1\n",
        "\n",
        "    df_rel_ranking = drop_unnamed(df_rel_ranking)\n",
        "    df_rand_ranking = drop_unnamed(df_rand_ranking)\n",
        "    df_date_ranking = drop_unnamed(df_date_ranking)\n",
        "\n",
        "    df_rel_ranking.to_csv(\"rel_ranking_\" + business_id + \".csv\")\n",
        "    df_date_ranking.to_csv(\"date_ranking_\" + business_id + \".csv\")\n",
        "    df_rand_ranking.to_csv(\"rand_ranking_\" + business_id + \".csv\")\n",
        "\n",
        "    #destination = set_file_destination('', 'ranking', business_id)\n",
        "    upload_file(\"rel_ranking_\" + business_id + \".csv\", folder_id)\n",
        "    upload_file(\"date_ranking_\" + business_id + \".csv\", folder_id)\n",
        "    upload_file(\"rand_ranking_\" + business_id + \".csv\", folder_id)\n",
        "\n",
        "\n",
        "def create_folder_in_drive(gdrive, folder_name, parent_folder_id):\n",
        "  folder_metadata = {'title': folder_name,'mimeType': 'application/vnd.google-apps.folder',\n",
        "                    'parents': [{\"kind\": \"drive#fileLink\", \"id\": parent_folder_id}]\n",
        "                    }\n",
        "  folder = gdrive.CreateFile(folder_metadata)\n",
        "  folder.Upload()\n",
        "  print(folder)\n",
        "  # Return folder informations\n",
        "  print('title: %s, id: %s' % (folder['title'], folder['id']))\n",
        "  return folder['id']\n",
        "\n",
        "\n",
        "numrest = 87\n",
        "id_lista = restaurants_id_list[numrest-10:]\n",
        "for id in id_lista:\n",
        "\n",
        "  download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "  download.GetContentFile('gtree.csv')\n",
        "  gtree = pd.read_csv('gtree.csv')\n",
        "\n",
        "  gfolder_id = create_folder_in_drive(drive, str(numrest) + ' - ' + id, '1p9X-C0p1191dYlRnrGUZZUkTXLymJ49_')\n",
        "  gfolder_rankings = create_folder_in_drive(drive, '1_rankings', gfolder_id)\n",
        "  gfolder_groups = create_folder_in_drive(drive, '2_groups_exposure', gfolder_id)\n",
        "  new_row = {'business_id':id, 'gfolder_id':gfolder_id, 'gfolder_rankings':gfolder_rankings, \n",
        "                              'gfolder_groups':gfolder_groups, 'gfolder_#11':'', 'gfolder_#12':'',\n",
        "                              'gfolder_#14':'', 'gfolder_userphoto':'', 'gfolder_clarifai':''}\n",
        "  gtree = gtree.append(new_row, ignore_index=True)\n",
        "  gtree = gtree.drop_duplicates('business_id',keep='last').reset_index(drop=True)\n",
        "  gtree = drop_unnamed(gtree)\n",
        "  gtree.to_csv('gtree.csv')\n",
        "  upload_file('gtree.csv', '1eUt2wyCOULW0-LdL6vyRJi1mUs_U46DD') # id folder data\n",
        "  retrieve_rankings(id, gfolder_rankings)\n",
        "  numrest += 1\n",
        "  print(id)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "0O6PjjOHV0y6",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "################################################################################\n",
        "###################### DOWNLOAD USER PHOTOS ####################################\n",
        "\n",
        "def downloadUser(business_id, user_id, photo_folder, counter):\n",
        "    authenticate()\n",
        "    \n",
        "    filename = user_id + '.jpg'\n",
        "    url = 'https://www.yelp.com/user_details?userid=' + user_id\n",
        "    folder_id = photo_folder\n",
        "\n",
        "    # CHECK DUPLICATE\n",
        "    fileList = drive.ListFile({'q': \"'\" + folder_id + \"' in parents and trashed=false\"}).GetList()\n",
        "    exists = False\n",
        "    # Check if file already exists in Google Drive (prevents duplicates)\n",
        "    for file in fileList:\n",
        "        if file['title'] == filename:  # The file already exists\n",
        "            exists = True\n",
        "    \n",
        "    if exists:\n",
        "      return True\n",
        "    else:\n",
        "      # Find user picture from web page\n",
        "      page_content = requests.get(url)\n",
        "      print(page_content)\n",
        "      if not page_content.ok:\n",
        "        return False\n",
        "      tree = html.fromstring(page_content.content)\n",
        "      if len(tree.xpath('//*[@id=\"wrap\"]/div[2]/div[1]/div/div[2]/div[1]/div/div/div/a/img/@src')) == 0:\n",
        "        print('PICTURE NOT FOUND')\n",
        "        print(user_id)\n",
        "        return False\n",
        "      else: # Picture found\n",
        "        image_url = tree.xpath('//*[@id=\"wrap\"]/div[2]/div[1]/div/div[2]/div[1]/div/div/div/a/img/@src')[0]\n",
        "\n",
        "        drive_file = drive.CreateFile({'title': filename, 'parents': [{'id': folder_id}]})\n",
        "      \n",
        "        response = requests.get(image_url, stream=True)\n",
        "\n",
        "        # Create a local copy of user picture\n",
        "        with open(filename, 'wb') as out_file:\n",
        "            shutil.copyfileobj(response.raw, out_file)\n",
        "        del response\n",
        "\n",
        "        # Upload user picture on Google Drive\n",
        "        drive_file.SetContentFile(filename)\n",
        "        drive_file.Upload()\n",
        "        if os.path.exists(filename):\n",
        "            os.remove(filename)\n",
        "        else:\n",
        "            print(\"The file does not exist\")\n",
        "        return True\n",
        "\n",
        "\n",
        "def scarica_tutti_utenti(business_id, df_utenti, photo_folder_id, startfrom):\n",
        "  df_utenti = df_utenti[startfrom:]\n",
        "  cnt = startfrom\n",
        "  for a, user in df_utenti.iterrows():\n",
        "    user_id = user['user_id']\n",
        "    completed = downloadUser(business_id, user_id, photo_folder_id, cnt)\n",
        "    if not completed:\n",
        "      print('ULTIMO SCARICATO:', cnt)\n",
        "      return False\n",
        "    print(cnt)\n",
        "    cnt = cnt + 1\n",
        "\n",
        "\n",
        "# DOWNLOAD restaurants.txt FROM DRIVE\n",
        "restaurants_dataset_id = '1BqMsph8flQMGmcE_WxYV0vSC_uqi-nge'  # FILE ID, got on google drive with condivision link\n",
        "download = drive.CreateFile({'id': restaurants_dataset_id})\n",
        "download.GetContentFile('restaurants.txt')\n",
        "with open('restaurants.txt') as f:\n",
        "    content = f.readlines()\n",
        "restaurants_id_list = [x.strip() for x in content] \n",
        "\n",
        "print(restaurants_id_list)\n",
        "\n",
        "\n",
        "numrest = 18\n",
        "id_lista = restaurants_id_list[(numrest-10):(numrest-9)]\n",
        "starting_from_photo = 2299\n",
        "\n",
        "\n",
        "download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "download.GetContentFile('gtree.csv')\n",
        "gtree = pd.read_csv('gtree.csv')\n",
        "\n",
        "for id in id_lista:\n",
        "  print(id)\n",
        "  user_ranking_folder = gtree.loc[gtree['business_id']==id, 'gfolder_rankings'].tolist()[0]\n",
        "  ranking_file = drive.ListFile({'q': \"'\" + user_ranking_folder + \"' in parents and trashed=false\"}).GetList()[0]  \n",
        "  download = drive.CreateFile({'id': ranking_file['id']})\n",
        "  download.GetContentFile('ranking_' + id + '.csv')\n",
        "  ranking = pd.read_csv('ranking_' + id + '.csv')\n",
        "  if starting_from_photo == 0:\n",
        "    id_cartella = create_folder_in_drive(drive, str(numrest) + ' - ' + id,\n",
        "                                         '12OKc1s2VeJRv5kUS_fp9f4dFLn1LkSPG')  # folder face_data>Foto_User\n",
        "    gtree.loc[gtree['business_id']==id, 'gfolder_userphoto'] = id_cartella\n",
        "    gtree = gtree.drop_duplicates('business_id',keep='last').reset_index(drop=True)\n",
        "    gtree = drop_unnamed(gtree)\n",
        "    gtree.to_csv('gtree.csv')\n",
        "    upload_file('gtree.csv', '1eUt2wyCOULW0-LdL6vyRJi1mUs_U46DD') # id folder data\n",
        "  else:\n",
        "    id_cartella = gtree.loc[gtree['business_id']==id, 'gfolder_userphoto'].tolist()[0]\n",
        "  \n",
        "  success = scarica_tutti_utenti(id, ranking[['user_id']], id_cartella, starting_from_photo)\n",
        "  if not success:\n",
        "    print('RISTORANTE:',id)\n",
        "    print(numrest)\n",
        "    break\n",
        "  else:\n",
        "    print(numrest)\n",
        "    print('FINE DOWNLOAD RISTORANTE ' + id)\n",
        "    numrest += 1\n"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "i4CE8fLjjUZw",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "################################################################################\n",
        "################## DOWNLOAD MISSING USER PHOTO #################################\n",
        "\n",
        "import json\n",
        "import csv\n",
        "import random\n",
        "import pandas as pd\n",
        "\n",
        "def scarica_utenti_mancanti(business_id, df_utenti, photo_folder_id):\n",
        "  cnt=0\n",
        "  for user_id in df_utenti:\n",
        "    completed = downloadUser(business_id, user_id, photo_folder_id, cnt)\n",
        "    if not completed:\n",
        "      print('ULTIMO NON SCARICATO:', user_id)\n",
        "      return False\n",
        "    print(cnt)\n",
        "    cnt = cnt + 1\n",
        "  return True\n",
        "\n",
        "\n",
        "# DOWNLOAD restaurants.txt FROM DRIVE\n",
        "restaurants_dataset_id = '1BqMsph8flQMGmcE_WxYV0vSC_uqi-nge'  # FILE ID, got on google drive with condivision link\n",
        "download = drive.CreateFile({'id': restaurants_dataset_id})\n",
        "download.GetContentFile('restaurants.txt')\n",
        "with open('restaurants.txt') as f:\n",
        "    content = f.readlines()\n",
        "restaurants_id_list = [x.strip() for x in content] \n",
        "\n",
        "print(restaurants_id_list)\n",
        "\n",
        "numrest = 74\n",
        "while numrest<75:\n",
        "\n",
        "  id = restaurants_id_list[(numrest-10):(numrest-9)][0]\n",
        "  download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "  download.GetContentFile('gtree.csv')\n",
        "  gtree = pd.read_csv('gtree.csv')\n",
        "\n",
        "  print(id)\n",
        "\n",
        "  user_photo_folder = gtree.loc[gtree['business_id']==id, 'gfolder_userphoto'].tolist()[0]\n",
        "  photo_list = drive.ListFile({'q': \"'\" + user_photo_folder + \"' in parents and trashed=false\"}).GetList() \n",
        "  user_id_list2 = [photo['title'][0:22] for photo in photo_list]\n",
        "  print(user_id_list2)\n",
        "\n",
        "  user_ranking_folder = gtree.loc[gtree['business_id']==id, 'gfolder_rankings'].tolist()[0]\n",
        "  ranking_file = drive.ListFile({'q': \"'\" + user_ranking_folder + \"' in parents and trashed=false\"}).GetList()[0]  \n",
        "  download = drive.CreateFile({'id': ranking_file['id']})\n",
        "  download.GetContentFile('ranking_' + id + '.csv')\n",
        "  ranking = pd.read_csv('ranking_' + id + '.csv')\n",
        "  user_id_list = ranking['user_id'].values.tolist()\n",
        "  print(user_id_list)\n",
        "\n",
        "  difference = (list(set(user_id_list) - set(user_id_list2)))\n",
        "\n",
        "  print('Utenti mancanti:', len(difference))\n",
        "  print(difference)\n",
        "  if difference:\n",
        "    success = scarica_utenti_mancanti(id, difference, user_photo_folder)\n",
        "  else:\n",
        "    success = True\n",
        "  if not success:\n",
        "    print('ERRORE RISTORANTE:',id)\n",
        "    print(numrest)\n",
        "    break\n",
        "  else:\n",
        "    print(numrest)\n",
        "    print('FINE DOWNLOAD RISTORANTE ' + id)\n",
        "    numrest += 1\n"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ZuTTwMxTYKxu",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "dce098d5-3eaf-4809-d6de-2d2f2da7ac03"
      },
      "source": [
        "################################################################################\n",
        "################ ELABORATE USER PHOTOS WITH CLARIFAI ###########################\n",
        "\n",
        "def detect_clarifai(id, url_photo):\n",
        "  app = ClarifaiApp(api_key='cc7fb2dd5d8745c9b235a5736fba2fc0 ')\n",
        "  model = app.models.get(model_id=\"c0c0ac362b03416da06ab3fa36fb58e3\")\n",
        "  response = model.predict_by_url(url = '%s' % url_photo)\n",
        "  \n",
        "  df_result = pd.DataFrame(columns=['user_id', 'age', 'gender', 'ethnicity'])\n",
        "\n",
        "  if response['outputs'][0]['data'] != {}:\n",
        "    x = 0\n",
        "    while (x < len(response['outputs'][0]['data']['regions'])):\n",
        "      age = response['outputs'][0]['data']['regions'][x]['data']['concepts'][0]['name']\n",
        "      gender = response['outputs'][0]['data']['regions'][x]['data']['concepts'][20]['name']\n",
        "      ethnicity = response['outputs'][0]['data']['regions'][x]['data']['concepts'][22]['name']\n",
        "\n",
        "      new_row = {'user_id':id,\n",
        "                 'age':age,\n",
        "                 'gender':gender,\n",
        "                 'ethnicity':ethnicity}\n",
        "      df_result = df_result.append(new_row, ignore_index=True)\n",
        "      x = x + 1\n",
        "  else:\n",
        "    new_row = {'user_id':id,\n",
        "              'age':np.NaN,\n",
        "              'gender':np.NaN,\n",
        "              'ethnicity':np.NaN}\n",
        "    df_result = df_result.append(new_row, ignore_index=True)\n",
        "  return df_result\n",
        "\n",
        "\n",
        "# LEGGO GTREE\n",
        "download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "download.GetContentFile('gtree.csv')\n",
        "gtree = pd.read_csv('gtree.csv')\n",
        "gtree = drop_unnamed(gtree)\n",
        "id_clarifai_folder = '1wfZ0d3cTufosLRhPKkShf7kQbJlUbBvH' # folder data > Clarifai\n",
        "\n",
        "# DOWNLOAD restaurants.txt FROM DRIVE\n",
        "restaurants_dataset_id = '1BqMsph8flQMGmcE_WxYV0vSC_uqi-nge'  # FILE ID, got on google drive with condivision link\n",
        "download = drive.CreateFile({'id': restaurants_dataset_id})\n",
        "download.GetContentFile('restaurants.txt')\n",
        "with open('restaurants.txt') as f:\n",
        "    content = f.readlines()\n",
        "restaurants_id_list = [x.strip() for x in content] \n",
        "\n",
        "print(restaurants_id_list)\n",
        "\n",
        "numrest = 19\n",
        "id_restaurant = restaurants_id_list[(numrest-10):(numrest-9)][0]\n",
        "startfrom = 0  # BE CAREFUL, IF 0 OVERWRITE THE CSV IN DRIVE\n",
        "\n",
        "id_photo_folder = gtree.loc[gtree['business_id'] == id_restaurant, 'gfolder_userphoto'].tolist()[0]\n",
        "print(id_restaurant)\n",
        "print(id_photo_folder)\n",
        "\n",
        "if startfrom == 0:\n",
        "  df_clarifai = pd.DataFrame(columns=['user_id', 'age', 'gender', 'ethnicity'])\n",
        "  df_clarifai.to_csv(str(numrest) + ' - ' + id_restaurant + '.csv')\n",
        "  id_new_file = upload_file(str(numrest) + ' - ' + id_restaurant + '.csv', id_clarifai_folder)\n",
        "  gtree.loc[gtree['business_id']==id_restaurant, 'gfolder_clarifai'] = id_new_file\n",
        "  gtree.to_csv('gtree.csv')\n",
        "  upload_file('gtree.csv', '1eUt2wyCOULW0-LdL6vyRJi1mUs_U46DD')\n",
        "else:\n",
        "  id_clarifai_file = gtree.loc[gtree['business_id']==id_restaurant, 'gfolder_clarifai'].tolist()[0]\n",
        "  download = drive.CreateFile({'id': id_clarifai_file})\n",
        "  download.GetContentFile(str(numrest) + ' - ' + id_restaurant + '.csv')\n",
        "  df_clarifai = pd.read_csv(str(numrest) + ' - ' + id_restaurant + '.csv')\n",
        "\n",
        "file_list = drive.ListFile({'q': \"'\" + id_photo_folder + \"' in parents and trashed=false\"}).GetList()    #cartella da cui prendo le foto\n",
        "\n",
        "count = 0\n",
        "\n",
        "for photo in file_list[startfrom:]:\n",
        "  user_id = photo['title'][0:22] \n",
        "  count = count + 1\n",
        "  if user_id not in df_clarifai['user_id'].values:\n",
        "    minidf_result = detect_clarifai(user_id, photo['thumbnailLink'])\n",
        "    df_clarifai = df_clarifai.append(minidf_result, ignore_index=True)\n",
        "    df_clarifai = drop_unnamed(df_clarifai)\n",
        "    if count == 100:\n",
        "      count = 0\n",
        "      df_clarifai.to_csv(str(numrest) + ' - ' + id_restaurant + '.csv')\n",
        "      id_new_file = upload_file(str(numrest) + ' - ' + id_restaurant + '.csv', id_clarifai_folder)\n",
        "      print('csv caricato: ' + id_new_file)\n",
        "      \n",
        "    print(startfrom)\n",
        "    startfrom = startfrom + 1\n",
        "  else:\n",
        "    if count == 100:\n",
        "      count = 0\n",
        "    print(str(startfrom) + ' già fatto')\n",
        "    startfrom = startfrom + 1\n",
        "      \n",
        "df_clarifai.to_csv(str(numrest) + ' - ' + id_restaurant + '.csv')\n",
        "id_new_file = upload_file(str(numrest) + ' - ' + id_restaurant + '.csv', id_clarifai_folder)\n",
        "print('csv caricato: ' + id_new_file) "
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "['VyVIneSU7XAWgMBllI6LnQ', 'pSQFynH1VxkfSmehRXlZWw', 'JzOp695tclcNCNMuBl7oxA', 'OgJ0KxwJcJ9R5bUK0ixCbg', '3l54GTr8-E3XPbIxnF_sAA', '9a3DrZvpYxVs3k_qwlCNSw', 'frCxZS7lPhEnQRJ3UY6m7A', 'yNPh5SO-7wr8HPpVCDPbXQ', '0FUtlsQrJI7LhqDPxLumEw', 'K-uQkfSUTwu5LIwPB4b_vg', 'L2p0vO3fsS2LC6hhQo3CzA', 'd10IxZPirVJlOSpdRZJczA', 'wUKzaS1MHg94RGM6z8u9mw', 'z6-reuC5BYf_Rth9gMBfgQ', 'aiX_WP7NKPTdF9CfI-M-wg', '3C5Z9homtzkWHouH2BHXYQ', 'C8D_GU9cDDjbOJfCaGXxDQ', 'Yl05MqCs9xRzrJFkGWLpgA', 'eS29S_06lvsDW04wVrIVxg', 'IsoLzudHC50oJLiEWpwV-w', '3N9U549Zse8UP-MwKZAjAQ', '_XN-GwzZwAyIqLKJsl2htg', 'r5PLDU-4mSbde5XekTXSCA', 'Iq7NqQD-sESu3vr9iEGuTA', 'u-SJ5QUwrNquL9VnXwl8cg', 'sJNcipFYElitBrtiJx0ezQ', '7m1Oa1VYV98UUuo_6i0EZg', 'e4NQLZynhSmvwl38hC4m-A', 'k1QpHAkzKTrFYfk6u--VgQ', '-6tvduBzjLI1ISfs3F_qTg', 'jcasci3gjbsSuTEVzvDQKg', 'Ch7NAhB_MWSDwcNbcptEKg', 'eZDXz_RylvdD0tHEA8I0NA', 'tCSlpwJQ4CZsUEMZeH2SFg', 'yWUBX9Pe6pzh1PjVj04UmQ', 'k-drEjxKmfqllwfY90STfA', 'y1eeVRfJa22CCpUCeNfrSw', 'VH3WA7a-OVzFj2K_SP4BIw', 'osSwv6CJy5hDKQdOKeyTow', 'o5QDrg_kb4hgsWxV6cV_Uw', 'XgRljuEUyaHBKIpIz-PRAA', 'wArcCMVnrl_tc9MULW-0CQ', 'SHFlELFcEcAOJv_fTAKChQ', 'aBLx9JlAMq_AuW6VAImSwg', 'd8lmIZIqmBC9oPM8y1dc7Q', 'bzbNGyrTwWHAgg1CqkSgeg', 'ADgacmZ-qXrSOhMfU6bmTA', 'gChmBjLSe3qa8rzEngoDLQ', 'D2ojX9bvE0_-aIj9BhdZZA', 'hggVnGwA5042-ABxqeJX-A', '9dqdzRzjSfbnMvjUGqWBAw', 'DyOzNIeXUksPNLXYHnB-oQ', 'mC39IrCp36QIVFRZIw9PTQ', 'sdYkVaTy7EJwUkO8Ie_qPg', 'ALwAlxItASeEs2vYAeLXHA', '01fuY2NNscttoTxOYbuZXw', 'T2tEMLpTeSMxLKpxwFdS3g', 'RVQE2Z2uky4c0-njFQO66g', 'WbJ1LRQdOuYYlRLyTkuuxw', 'RAh9WCQAuocM7hYM5_6tnw', '3kdSl5mo9dWC4clrQjEDGg', '7sPNbCx7vGAaH7SbNPZ6oA', 'Cni2l-VKG_pdospJ6xliXQ', 'DkYS3arLOhA8si5uUEmHOw', 'f4x1YBxkLrZg652xt2KR5g', 'faPVqws-x-5k2CQKDNtHxw', 'fL-b760btOaGa85OJ9ut3w', 'G-5kEa6E6PD5fkBRuA7k9Q', 'g8OnV26ywJlZpezdBnOWUQ', 'HhVmDybpU7L50Kb5A0jXTg', 'hihud--QRriCYZw1zZvW4g', 'IWN2heYitkg-D4UdqfxcMA', 'JDZ6_yycNQFTpUZzLIKHUg', 'JpgVl3d20CMRNjf1DVnzGA', 'mDR12Hafvr84ctpsV6YLag', 'NvKNe9DnQavC9GstglcBJQ', 'OETh78qcgDltvHULowwhJg', 'P7pxQFqr7yBKMMI2J51udw', 'pH0BLkL4cbxKzu471VZnuA', 'QJatAcxYgK1Zp9BRZMAx7g', 'QXV3L_QFGj8r6nWX2kS2hA', 'RwMLuOkImBIqqYj4SSKSPg', 'ujHiaprwCQ5ewziu0Vi9rw', 'UPIYuRaZvknINOd1w8kqRQ', 'xkVMIk_Vqh17f48ZQ_6b0w', 'XXW_OFaYQkkGOGniujZFHg', 'XZbuPXdyA0ZtTu3AzqtQhg', 'yfxDa8RFOvJPQh0rNtakHA', 'YJ8ljUhLsz6CtT_2ORNFmg', 'ZkGDCVKSdf8m76cnnalL-A']\n",
            "K-uQkfSUTwu5LIwPB4b_vg\n",
            "1RL1CmWflFpWym4OqFyibFmea2MrEX61w\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "0\n",
            "1\n",
            "2\n",
            "3\n",
            "4\n",
            "5\n",
            "6\n",
            "7\n",
            "8\n",
            "9\n",
            "10\n",
            "11\n",
            "12\n",
            "13\n",
            "14\n",
            "15\n",
            "16\n",
            "17\n",
            "18\n",
            "19\n",
            "20\n",
            "21\n",
            "22\n",
            "23\n",
            "24\n",
            "25\n",
            "26\n",
            "27\n",
            "28\n",
            "29\n",
            "30\n",
            "31\n",
            "32\n",
            "33\n",
            "34\n",
            "35\n",
            "36\n",
            "37\n",
            "38\n",
            "39\n",
            "40\n",
            "41\n",
            "42\n",
            "43\n",
            "44\n",
            "45\n",
            "46\n",
            "47\n",
            "48\n",
            "49\n",
            "50\n",
            "51\n",
            "52\n",
            "53\n",
            "54\n",
            "55\n",
            "56\n",
            "57\n",
            "58\n",
            "59\n",
            "60\n",
            "61\n",
            "62\n",
            "63\n",
            "64\n",
            "65\n",
            "66\n",
            "67\n",
            "68\n",
            "69\n",
            "70\n",
            "71\n",
            "72\n",
            "73\n",
            "74\n",
            "75\n",
            "76\n",
            "77\n",
            "78\n",
            "79\n",
            "80\n",
            "81\n",
            "82\n",
            "83\n",
            "84\n",
            "85\n",
            "86\n",
            "87\n",
            "88\n",
            "89\n",
            "90\n",
            "91\n",
            "92\n",
            "93\n",
            "94\n",
            "95\n",
            "96\n",
            "97\n",
            "98\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "99\n",
            "100\n",
            "101\n",
            "102\n",
            "103\n",
            "104\n",
            "105\n",
            "106\n",
            "107\n",
            "108\n",
            "109\n",
            "110\n",
            "111\n",
            "112\n",
            "113\n",
            "114\n",
            "115\n",
            "116\n",
            "117\n",
            "118\n",
            "119\n",
            "120\n",
            "121\n",
            "122\n",
            "123\n",
            "124\n",
            "125\n",
            "126\n",
            "127\n",
            "128\n",
            "129\n",
            "130\n",
            "131\n",
            "132\n",
            "133\n",
            "134\n",
            "135\n",
            "136\n",
            "137\n",
            "138\n",
            "139\n",
            "140\n",
            "141\n",
            "142\n",
            "143\n",
            "144\n",
            "145\n",
            "146\n",
            "147\n",
            "148\n",
            "149\n",
            "150\n",
            "151\n",
            "152\n",
            "153\n",
            "154\n",
            "155\n",
            "156\n",
            "157\n",
            "158\n",
            "159\n",
            "160\n",
            "161\n",
            "162\n",
            "163\n",
            "164\n",
            "165\n",
            "166\n",
            "167\n",
            "168\n",
            "169\n",
            "170\n",
            "171\n",
            "172\n",
            "173\n",
            "174\n",
            "175\n",
            "176\n",
            "177\n",
            "178\n",
            "179\n",
            "180\n",
            "181\n",
            "182\n",
            "183\n",
            "184\n",
            "185\n",
            "186\n",
            "187\n",
            "188\n",
            "189\n",
            "190\n",
            "191\n",
            "192\n",
            "193\n",
            "194\n",
            "195\n",
            "196\n",
            "197\n",
            "198\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "199\n",
            "200\n",
            "201\n",
            "202\n",
            "203\n",
            "204\n",
            "205\n",
            "206\n",
            "207\n",
            "208\n",
            "209\n",
            "210\n",
            "211\n",
            "212\n",
            "213\n",
            "214\n",
            "215\n",
            "216\n",
            "217\n",
            "218\n",
            "219\n",
            "220\n",
            "221\n",
            "222\n",
            "223\n",
            "224\n",
            "225\n",
            "226\n",
            "227\n",
            "228\n",
            "229\n",
            "230\n",
            "231\n",
            "232\n",
            "233\n",
            "234\n",
            "235\n",
            "236\n",
            "237\n",
            "238\n",
            "239\n",
            "240\n",
            "241\n",
            "242\n",
            "243\n",
            "244\n",
            "245\n",
            "246\n",
            "247\n",
            "248\n",
            "249\n",
            "250\n",
            "251\n",
            "252\n",
            "253\n",
            "254\n",
            "255\n",
            "256\n",
            "257\n",
            "258\n",
            "259\n",
            "260\n",
            "261\n",
            "262\n",
            "263\n",
            "264\n",
            "265\n",
            "266\n",
            "267\n",
            "268\n",
            "269\n",
            "270\n",
            "271\n",
            "272\n",
            "273\n",
            "274\n",
            "275\n",
            "276\n",
            "277\n",
            "278\n",
            "279\n",
            "280\n",
            "281\n",
            "282\n",
            "283\n",
            "284\n",
            "285\n",
            "286\n",
            "287\n",
            "288\n",
            "289\n",
            "290\n",
            "291\n",
            "292\n",
            "293\n",
            "294\n",
            "295\n",
            "296\n",
            "297\n",
            "298\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "299\n",
            "300\n",
            "301\n",
            "302\n",
            "303\n",
            "304\n",
            "305\n",
            "306\n",
            "307\n",
            "308\n",
            "309\n",
            "310\n",
            "311\n",
            "312\n",
            "313\n",
            "314\n",
            "315\n",
            "316\n",
            "317\n",
            "318\n",
            "319\n",
            "320\n",
            "321\n",
            "322\n",
            "323\n",
            "324\n",
            "325\n",
            "326\n",
            "327\n",
            "328\n",
            "329\n",
            "330\n",
            "331\n",
            "332\n",
            "333\n",
            "334\n",
            "335\n",
            "336\n",
            "337\n",
            "338\n",
            "339\n",
            "340\n",
            "341\n",
            "342\n",
            "343\n",
            "344\n",
            "345\n",
            "346\n",
            "347\n",
            "348\n",
            "349\n",
            "350\n",
            "351\n",
            "352\n",
            "353\n",
            "354\n",
            "355\n",
            "356\n",
            "357\n",
            "358\n",
            "359\n",
            "360\n",
            "361\n",
            "362\n",
            "363\n",
            "364\n",
            "365\n",
            "366\n",
            "367\n",
            "368\n",
            "369\n",
            "370\n",
            "371\n",
            "372\n",
            "373\n",
            "374\n",
            "375\n",
            "376\n",
            "377\n",
            "378\n",
            "379\n",
            "380\n",
            "381\n",
            "382\n",
            "383\n",
            "384\n",
            "385\n",
            "386\n",
            "387\n",
            "388\n",
            "389\n",
            "390\n",
            "391\n",
            "392\n",
            "393\n",
            "394\n",
            "395\n",
            "396\n",
            "397\n",
            "398\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "399\n",
            "400\n",
            "401\n",
            "402\n",
            "403\n",
            "404\n",
            "405\n",
            "406\n",
            "407\n",
            "408\n",
            "409\n",
            "410\n",
            "411\n",
            "412\n",
            "413\n",
            "414\n",
            "415\n",
            "416\n",
            "417\n",
            "418\n",
            "419\n",
            "420\n",
            "421\n",
            "422\n",
            "423\n",
            "424\n",
            "425\n",
            "426\n",
            "427\n",
            "428\n",
            "429\n",
            "430\n",
            "431\n",
            "432\n",
            "433\n",
            "434\n",
            "435\n",
            "436\n",
            "437\n",
            "438\n",
            "439\n",
            "440\n",
            "441\n",
            "442\n",
            "443\n",
            "444\n",
            "445\n",
            "446\n",
            "447\n",
            "448\n",
            "449\n",
            "450\n",
            "451\n",
            "452\n",
            "453\n",
            "454\n",
            "455\n",
            "456\n",
            "457\n",
            "458\n",
            "459\n",
            "460\n",
            "461\n",
            "462\n",
            "463\n",
            "464\n",
            "465\n",
            "466\n",
            "467\n",
            "468\n",
            "469\n",
            "470\n",
            "471\n",
            "472\n",
            "473\n",
            "474\n",
            "475\n",
            "476\n",
            "477\n",
            "478\n",
            "479\n",
            "480\n",
            "481\n",
            "482\n",
            "483\n",
            "484\n",
            "485\n",
            "486\n",
            "487\n",
            "488\n",
            "489\n",
            "490\n",
            "491\n",
            "492\n",
            "493\n",
            "494\n",
            "495\n",
            "496\n",
            "497\n",
            "498\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "499\n",
            "500\n",
            "501\n",
            "502\n",
            "503\n",
            "504\n",
            "505\n",
            "506\n",
            "507\n",
            "508\n",
            "509\n",
            "510\n",
            "511\n",
            "512\n",
            "513\n",
            "514\n",
            "515\n",
            "516\n",
            "517\n",
            "518\n",
            "519\n",
            "520\n",
            "521\n",
            "522\n",
            "523\n",
            "524\n",
            "525\n",
            "526\n",
            "527\n",
            "528\n",
            "529\n",
            "530\n",
            "531\n",
            "532\n",
            "533\n",
            "534\n",
            "535\n",
            "536\n",
            "537\n",
            "538\n",
            "539\n",
            "540\n",
            "541\n",
            "542\n",
            "543\n",
            "544\n",
            "545\n",
            "546\n",
            "547\n",
            "548\n",
            "549\n",
            "550\n",
            "551\n",
            "552\n",
            "553\n",
            "554\n",
            "555\n",
            "556\n",
            "557\n",
            "558\n",
            "559\n",
            "560\n",
            "561\n",
            "562\n",
            "563\n",
            "564\n",
            "565\n",
            "566\n",
            "567\n",
            "568\n",
            "569\n",
            "570\n",
            "571\n",
            "572\n",
            "573\n",
            "574\n",
            "575\n",
            "576\n",
            "577\n",
            "578\n",
            "579\n",
            "580\n",
            "581\n",
            "582\n",
            "583\n",
            "584\n",
            "585\n",
            "586\n",
            "587\n",
            "588\n",
            "589\n",
            "590\n",
            "591\n",
            "592\n",
            "593\n",
            "594\n",
            "595\n",
            "596\n",
            "597\n",
            "598\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "599\n",
            "600\n",
            "601\n",
            "602\n",
            "603\n",
            "604\n",
            "605\n",
            "606\n",
            "607\n",
            "608\n",
            "609\n",
            "610\n",
            "611\n",
            "612\n",
            "613\n",
            "614\n",
            "615\n",
            "616\n",
            "617\n",
            "618\n",
            "619\n",
            "620\n",
            "621\n",
            "622\n",
            "623\n",
            "624\n",
            "625\n",
            "626\n",
            "627\n",
            "628\n",
            "629\n",
            "630\n",
            "631\n",
            "632\n",
            "633\n",
            "634\n",
            "635\n",
            "636\n",
            "637\n",
            "638\n",
            "639\n",
            "640\n",
            "641\n",
            "642\n",
            "643\n",
            "644\n",
            "645\n",
            "646\n",
            "647\n",
            "648\n",
            "649\n",
            "650\n",
            "651\n",
            "652\n",
            "653\n",
            "654\n",
            "655\n",
            "656\n",
            "657\n",
            "658\n",
            "659\n",
            "660\n",
            "661\n",
            "662\n",
            "663\n",
            "664\n",
            "665\n",
            "666\n",
            "667\n",
            "668\n",
            "669\n",
            "670\n",
            "671\n",
            "672\n",
            "673\n",
            "674\n",
            "675\n",
            "676\n",
            "677\n",
            "678\n",
            "679\n",
            "680\n",
            "681\n",
            "682\n",
            "683\n",
            "684\n",
            "685\n",
            "686\n",
            "687\n",
            "688\n",
            "689\n",
            "690\n",
            "691\n",
            "692\n",
            "693\n",
            "694\n",
            "695\n",
            "696\n",
            "697\n",
            "698\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "699\n",
            "700\n",
            "701\n",
            "702\n",
            "703\n",
            "704\n",
            "705\n",
            "706\n",
            "707\n",
            "708\n",
            "709\n",
            "710\n",
            "711\n",
            "712\n",
            "713\n",
            "714\n",
            "715\n",
            "716\n",
            "717\n",
            "718\n",
            "719\n",
            "720\n",
            "721\n",
            "722\n",
            "723\n",
            "724\n",
            "725\n",
            "726\n",
            "727\n",
            "728\n",
            "729\n",
            "730\n",
            "731\n",
            "732\n",
            "733\n",
            "734\n",
            "735\n",
            "736\n",
            "737\n",
            "738\n",
            "739\n",
            "740\n",
            "741\n",
            "742\n",
            "743\n",
            "744\n",
            "745\n",
            "746\n",
            "747\n",
            "748\n",
            "749\n",
            "750\n",
            "751\n",
            "752\n",
            "753\n",
            "754\n",
            "755\n",
            "756\n",
            "757\n",
            "758\n",
            "759\n",
            "760\n",
            "761\n",
            "762\n",
            "763\n",
            "764\n",
            "765\n",
            "766\n",
            "767\n",
            "768\n",
            "769\n",
            "770\n",
            "771\n",
            "772\n",
            "773\n",
            "774\n",
            "775\n",
            "776\n",
            "777\n",
            "778\n",
            "779\n",
            "780\n",
            "781\n",
            "782\n",
            "783\n",
            "784\n",
            "785\n",
            "786\n",
            "787\n",
            "788\n",
            "789\n",
            "790\n",
            "791\n",
            "792\n",
            "793\n",
            "794\n",
            "795\n",
            "796\n",
            "797\n",
            "798\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "799\n",
            "800\n",
            "801\n",
            "802\n",
            "803\n",
            "804\n",
            "805\n",
            "806\n",
            "807\n",
            "808\n",
            "809\n",
            "810\n",
            "811\n",
            "812\n",
            "813\n",
            "814\n",
            "815\n",
            "816\n",
            "817\n",
            "818\n",
            "819\n",
            "820\n",
            "821\n",
            "822\n",
            "823\n",
            "824\n",
            "825\n",
            "826\n",
            "827\n",
            "828\n",
            "829\n",
            "830\n",
            "831\n",
            "832\n",
            "833\n",
            "834\n",
            "835\n",
            "836\n",
            "837\n",
            "838\n",
            "839\n",
            "840\n",
            "841\n",
            "842\n",
            "843\n",
            "844\n",
            "845\n",
            "846\n",
            "847\n",
            "848\n",
            "849\n",
            "850\n",
            "851\n",
            "852\n",
            "853\n",
            "854\n",
            "855\n",
            "856\n",
            "857\n",
            "858\n",
            "859\n",
            "860\n",
            "861\n",
            "862\n",
            "863\n",
            "864\n",
            "865\n",
            "866\n",
            "867\n",
            "868\n",
            "869\n",
            "870\n",
            "871\n",
            "872\n",
            "873\n",
            "874\n",
            "875\n",
            "876\n",
            "877\n",
            "878\n",
            "879\n",
            "880\n",
            "881\n",
            "882\n",
            "883\n",
            "884\n",
            "885\n",
            "886\n",
            "887\n",
            "888\n",
            "889\n",
            "890\n",
            "891\n",
            "892\n",
            "893\n",
            "894\n",
            "895\n",
            "896\n",
            "897\n",
            "898\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 36, in autodetect\n",
            "    from google.appengine.api import memcache\n",
            "ModuleNotFoundError: No module named 'google.appengine'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 33, in <module>\n",
            "    from oauth2client.contrib.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 37, in <module>\n",
            "    from oauth2client.locked_file import LockedFile\n",
            "ModuleNotFoundError: No module named 'oauth2client.locked_file'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/__init__.py\", line 42, in autodetect\n",
            "    from . import file_cache\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery_cache/file_cache.py\", line 41, in <module>\n",
            "    \"file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\"\n",
            "ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth\n"
          ],
          "name": "stderr"
        },
        {
          "output_type": "stream",
          "text": [
            "csv caricato: 1TwJ8l0tvpLStvHOl3nIz0s7qgXBmkQeF\n",
            "899\n",
            "900\n",
            "901\n",
            "902\n",
            "903\n",
            "904\n",
            "905\n",
            "906\n",
            "907\n",
            "908\n",
            "910\n",
            "911\n",
            "912\n",
            "913\n",
            "914\n",
            "915\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "S3g-ePyz_VHi",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "################################################################################\n",
        "############################### CHECK NUMBERS ##################################\n",
        "\n",
        "download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "download.GetContentFile('gtree.csv')\n",
        "gtree = pd.read_csv('gtree.csv')\n",
        "gtree = drop_unnamed(gtree)\n",
        "\n",
        "# DOWNLOAD restaurants.txt FROM DRIVE\n",
        "restaurants_dataset_id = '1BqMsph8flQMGmcE_WxYV0vSC_uqi-nge'  # FILE ID, got on google drive with condivision link\n",
        "download = drive.CreateFile({'id': restaurants_dataset_id})\n",
        "download.GetContentFile('restaurants.txt')\n",
        "with open('restaurants.txt') as f:\n",
        "    content = f.readlines()\n",
        "restaurants_id_list = [x.strip() for x in content] \n",
        "\n",
        "print(restaurants_id_list)\n",
        "\n",
        "numero_risto = 69\n",
        "\n",
        "while numero_risto < 71:\n",
        "  print(numero_risto)\n",
        "  id_risto = restaurants_id_list[(numero_risto-10):(numero_risto-9)][0]\n",
        "  print(id_risto)\n",
        "\n",
        "  ########################## RANKING ##############################\n",
        "  user_ranking_folder = gtree.loc[gtree['business_id']==id_risto, 'gfolder_rankings'].tolist()[0]\n",
        "  ranking_file = drive.ListFile({'q': \"'\" + user_ranking_folder + \"' in parents and trashed=false\"}).GetList()[0]  \n",
        "  download = drive.CreateFile({'id': ranking_file['id']})\n",
        "  download.GetContentFile('ranking_' + id_risto + '.csv')\n",
        "  file_ranking = pd.read_csv('ranking_' + id_risto + '.csv')\n",
        "  ranking_lista = file_ranking['user_id'].values.tolist()\n",
        "\n",
        "  ########################## PHOTO ##############################\n",
        "  user_photo_folder = gtree.loc[gtree['business_id']==id_risto, 'gfolder_userphoto'].tolist()[0]\n",
        "  photo_lista = drive.ListFile({'q': \"'\" + user_photo_folder + \"' in parents and trashed=false\"}).GetList() \n",
        "  photo_lista = [photo['title'][0:22] for photo in photo_lista]\n",
        "  seen = set()\n",
        "  print('duplicates:')\n",
        "  for x in photo_lista:\n",
        "    if x not in seen:\n",
        "        seen.add(x)\n",
        "    else:\n",
        "      print(x)\n",
        "\n",
        "  ########################## CLARIFAI ##############################\n",
        "  user_clarifai_id = gtree.loc[gtree['business_id']==id_risto, 'gfolder_clarifai'].tolist()[0]\n",
        "  download = drive.CreateFile({'id': user_clarifai_id})\n",
        "  download.GetContentFile('clarifai_' + id_risto + '.csv')\n",
        "  file_clarifai = pd.read_csv('clarifai_' + id_risto + '.csv')\n",
        "\n",
        "  print('tot ranking = tot foto = tot clarifai')\n",
        "  tot_ranking = len(file_ranking.index)\n",
        "  tot_foto = len(photo_lista)\n",
        "  tot_clarifai = len(file_clarifai.drop_duplicates(subset=('user_id')).reset_index().index)\n",
        "\n",
        "  print(str(tot_ranking) + ' = ' + str(tot_foto) + ' = ' + str(tot_clarifai))\n",
        "  if tot_ranking!=tot_foto or tot_ranking!=tot_clarifai or tot_foto!=tot_clarifai:\n",
        "    for unid in ranking_lista:\n",
        "      if unid not in photo_lista:\n",
        "        print(unid) \n",
        "  numero_risto += 1\n"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "uADbgKK-9U9_",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "################################################################################\n",
        "#################### MODIFY SOME VALUES IN GTREE ###############################\n",
        "\n",
        "download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "download.GetContentFile('gtree.csv')\n",
        "df = pd.read_csv('gtree.csv')\n",
        "df = drop_unnamed(df)\n",
        "\n",
        "#BE CAREFUL AT THE INDEX\n",
        "indice = 31  # IF RESTAURANT 20, THEN 10 IN GTREE\n",
        "#df.loc[indice, 'business_id'] = ''\n",
        "#df.loc[indice, 'gfolder_id'] = ''\n",
        "#df.loc[indice, 'gfolder_rankings'] = ''\n",
        "#df.loc[indice, 'gfolder_groups'] = ''\n",
        "#df.loc[indice, 'gfolder_userphoto'] = ''\n",
        "df.loc[indice, 'gfolder_clarifai'] = ''\n",
        "\n",
        "gtree = drop_unnamed(df)\n",
        "gtree.to_csv('gtree.csv')\n",
        "upload_file('gtree.csv', '1eUt2wyCOULW0-LdL6vyRJi1mUs_U46DD') # id folder data"
      ],
      "execution_count": 8,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "eRNS1d5oV_3W",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "################################################################################\n",
        "######################## INSERT ONE ROW IN GTREE ###############################\n",
        "\n",
        "def Insert_row(row_number, df, row_value):\n",
        "    start_upper = 0\n",
        "    end_upper = row_number\n",
        "    start_lower = row_number\n",
        "    end_lower = df.shape[0]\n",
        "    upper_half = [*range(start_upper, end_upper, 1)]\n",
        "    lower_half = [*range(start_lower, end_lower, 1)]\n",
        "    lower_half = [x.__add__(1) for x in lower_half]\n",
        "    index_ = upper_half + lower_half\n",
        "    df.index = index_\n",
        "    df.loc[row_number] = row_value\n",
        "    df = df.sort_index()\n",
        "    return df \n",
        "\n",
        "download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "download.GetContentFile('gtree.csv')\n",
        "df = pd.read_csv('gtree.csv')\n",
        "print(df)\n",
        "df = drop_unnamed(df)\n",
        " \n",
        "row_number = 66\n",
        "row_value = ['fL-b760btOaGa85OJ9ut3w', '1DhrpTWJygfaPrYkHNH1xuz-HxWZBZe__',\n",
        "             '1Vm5kyWMQQCSMBLSGpDwVfHIR4bp5-JIt', '19bUEYHBUGKxt7DjStk0qJIlqq4NKslw8',\n",
        "             '','','','','']\n",
        "  \n",
        "if row_number > df.index.max()+1: \n",
        "  print(\"Invalid row_number\") \n",
        "else:\n",
        "  df = Insert_row(row_number, df, row_value) \n",
        "  print(df[row_number-1:])\n",
        "\n",
        "gtree = drop_unnamed(df)\n",
        "gtree.to_csv('gtree.csv')\n",
        "upload_file('gtree.csv', '1eUt2wyCOULW0-LdL6vyRJi1mUs_U46DD') # id folder data"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "zzJX2f82v1e_",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 277
        },
        "outputId": "d1f65f0d-f2ac-425f-8828-3317d026ce38"
      },
      "source": [
        "################################################################################\n",
        "##################### INSERT ROWS AT BEGIN IN GTREE ############################\n",
        "\n",
        "download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "download.GetContentFile('gtree.csv')\n",
        "gtree = pd.read_csv('gtree.csv')\n",
        "\n",
        "values = [['WbJ1LRQdOuYYlRLyTkuuxw','1DFANWg2Io81FaV_GxlwBWfpG9Bx-Dgr7','1U0Ml5puObfOk3qHCKhO9bQ06WyhJoffW','1Ba-IYi1icz5tuO_AYN-f-FvjXjA5NmJi','','','','19r7YGFp7oAqItv63TZOPyAt4hDa_UyRr',''],\n",
        "          ['T2tEMLpTeSMxLKpxwFdS3g','1ENW6Pyiyt7v6p54Uhn9zrM9HQ28MB1-G','136FZ0Y90Zx-4UYDyW50cX8zUa_DhN3XS','1wAgWQ6Vmy3fe-RJ8_Ezwow75ftvOFP5_','','','','1f1NhSvHMwyJOxIrGbDix1lQ5NN4eHoG4',''],\n",
        "          ['ALwAlxItASeEs2vYAeLXHA','1oEws_0F-s4hS6CpBxqxuzoJ2Wo-Nf8eL','12zXi3XyQaNgukGHW_805cyrkHhSdF7Df','1lZKqsV-sTAEOnLv-MQxpdao7eBWkjKP1','','','','1mWA3-mH9Kl0Xho24he8__4nZJBVPx9Qh',''],\n",
        "          ['OVTZNSkSfbl3gVB9XQIJfw','1hgql_Ey5epZKj-SuB4F5Fu1eYOd2P8RX','1ZyNQavpG0akr3ca3PJjjl_D89IA5wlcc','1-drKKIaitJ0tjEY1W80B3kRXI5Ive5lC','','','','1OqlKSXZUvZCOOmTAONENS9Sq0twMCRM8',''],\n",
        "          ['Sovgwq-E-n6wLqNh3X_rXg','10fJv8tOFOwBiAZBVEedsqxi3g6zYLxjD','1EZqvt9x5PN07BgUad1RtNIUXTVqujA0g','1QcSsJsvQne8a9jMvL9_1VAmeGIrsq8R8','','','','1ArjfNsamdhSpG7BJwnJZ_qULh_aklp62',''],\n",
        "          ['j5nPiTwWEFr-VsePew7Sjg','1yRDL_lrQFsCijdyvDssRgdZ5a2wyjCXj','18bQVXYZ03vIpfEFLPh8I2i7cPTlokGxv','1VysI0VkliBEU8Y1sCX0PU9eKYE6GaCzC','','','','1KW9VPvY33rbkgPfzrREpxMfSQJg4xxoL',''],\n",
        "          ['aiX_WP7NKPTdF9CfI-M-wg','1lQu_nXTCrzMFOm3uuXmCNVzx0PmYv0Of','1nl6A997UnuR5ceYRZS1242JJCvK-Sf_u','12Z4PEBlcTkz6kjeJ0JYRKI3WCrjRi4bF','','','','11H38dweaCKJ4-TD88nuzV70lMF5n4yzG',''],\n",
        "          ['e4NQLZynhSmvwl38hC4m-A','1f3bGHoK6Hy44pKRqSsnhN8KM-W3AAChW','1K566Y5Q2N6Lw7S6yDicKC_R-zFVRqnFr','1reeSQL8MfkxOQg-NsVxazVdKfG1XNPEF','','','','1fVLmOBbg44H8q_UcwAOQiX6CeN6hf84Z',''],\n",
        "          ['S-oLPRdhlyL5HAknBKTUcQ','1bG_50_Yyh9vq7YDQ3zSNTqS4acm1Cs7x','1FJqfJgaJinXS3oIvdA53FMuO9O7bCDVn','17QEFZUC_rhrLk9mSDXoegq7TSCI2_JLS','','','','1CMUT4RhSeuPi0j4VGoLCe-iP9-Aj5Fsy','']]\n",
        "          \n",
        "df1=pd.DataFrame(values, columns=['business_id', 'gfolder_id', 'gfolder_rankings', \n",
        "                              'gfolder_groups', 'gfolder_#11', 'gfolder_#12',\n",
        "                              'gfolder_#14','gfolder_userphoto','gfolder_clarifai'])\n",
        "df2=gtree\n",
        "\n",
        "df3 = pd.concat([df1, df2]).reset_index(drop=True)\n",
        "df3 = drop_unnamed(df3)\n",
        "print(df3)\n",
        "df3.to_csv('gtree.csv')\n",
        "gtree = drop_unnamed(gtree)\n",
        "print(gtree)\n",
        "upload_file('gtree.csv', '1eUt2wyCOULW0-LdL6vyRJi1mUs_U46DD') # id folder data"
      ],
      "execution_count": 44,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "    #restaurant  ... gfolder_clarifai\n",
            "0             1  ...              NaN\n",
            "1             2  ...              NaN\n",
            "2             3  ...              NaN\n",
            "3             4  ...              NaN\n",
            "4             5  ...              NaN\n",
            "..          ...  ...              ...\n",
            "94           95  ...              NaN\n",
            "95           96  ...              NaN\n",
            "96           97  ...              NaN\n",
            "97           98  ...              NaN\n",
            "98           99  ...              NaN\n",
            "\n",
            "[99 rows x 10 columns]\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "'1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 44
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "K_T7KPQkFat3",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "################################################################################\n",
        "##################### ADD AND REORDER COLUMNS IN GTREE #########################\n",
        "\n",
        "download = drive.CreateFile({'id': '1MIWS9uI9GKxsgAlzB0wXFBiutE025u2c'}) # id file gtree.csv\n",
        "download.GetContentFile('gtree.csv')\n",
        "gtree = pd.read_csv('gtree.csv')\n",
        "\n",
        "gtree['#restaurant'] = gtree.index + 1\n",
        "cols = gtree.columns.tolist()\n",
        "cols = cols[-1:] + cols[:-1]\n",
        "gtree = gtree[cols]\n",
        "\n",
        "gtree = drop_unnamed(gtree)\n",
        "print(gtree)\n",
        "upload_file('gtree.csv', '1eUt2wyCOULW0-LdL6vyRJi1mUs_U46DD') # id folder data"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}